package Cliente;

import Mail.Fachada;
import Mail.IMail;
import java.util.Arrays;
import java.util.List;

public class FrameCliente extends javax.swing.JFrame {

    private IMail fachada;

    /**
     * Creates new form FrameCliente
     */
    public FrameCliente() {
        initComponents();
        fachada = new Fachada();
        this.llenarComboBox();
    }

    private void llenarComboBox() {
        String str = this.fachada.recuperarConfiguración();
        List<String> tokens = Arrays.asList(str.split("\\s*,\\s*"));
        for (int i = 0; i < tokens.size(); i++) {
            String get = tokens.get(i);
            this.jComboBoxConfiguración.addItem(get);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxConfiguración = new javax.swing.JComboBox<>();
        jButtonContinuar = new javax.swing.JButton();
        jLabelPrueba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal");
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenidos al simulador de entrega de correos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 50, 570, 28);

        jLabel2.setText("Arquitectura de Computadoras Agosto-Diciembre 2022");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 90, 310, 20);

        jLabel3.setText("Selecciones el tipo de configuración;");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 190, 220, 20);

        jComboBoxConfiguración.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConfiguraciónActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxConfiguración);
        jComboBoxConfiguración.setBounds(330, 180, 220, 40);

        jButtonContinuar.setText("Continuar");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinuar);
        jButtonContinuar.setBounds(280, 290, 90, 40);
        getContentPane().add(jLabelPrueba);
        jLabelPrueba.setBounds(120, 350, 490, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxConfiguraciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConfiguraciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxConfiguraciónActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCorreo((String) jComboBoxConfiguración.getSelectedItem()).setVisible(true);
            }
        });

    }//GEN-LAST:event_jButtonContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JComboBox<String> jComboBoxConfiguración;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPrueba;
    // End of variables declaration//GEN-END:variables
}
