
package Cliente;

import Mail.Fachada;
import Mail.IMail;
import Mensaje.MensajeCorreo;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class FrameCorreo extends javax.swing.JFrame {

    private String tipo;
    private IMail fachada;

    /**
     * Creates new form FrameCorreo
     * @param tipo
     */
    public FrameCorreo(String tipo) {
        initComponents();
        this.tipo = tipo;
        this.jLabelTitulo.setText(tipo);
        this.fachada = new Fachada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldRemitente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAsunto = new javax.swing.JTextField();
        jTextFieldDestinatario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextCuerpo = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButtonEnviar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextProgreso = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(430, 20, 260, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Progreso");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 380, 120, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Destinatario;");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 120, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Remitente;");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 80, 120, 30);

        jTextFieldRemitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRemitenteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldRemitente);
        jTextFieldRemitente.setBounds(170, 70, 330, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("Enviador de Correos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 20, 370, 30);

        jTextFieldAsunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAsuntoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAsunto);
        jTextFieldAsunto.setBounds(170, 180, 330, 40);

        jTextFieldDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDestinatarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDestinatario);
        jTextFieldDestinatario.setBounds(170, 130, 330, 40);

        jTextCuerpo.setColumns(20);
        jTextCuerpo.setRows(5);
        jScrollPane1.setViewportView(jTextCuerpo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 240, 330, 110);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Asunto;");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 120, 30);

        jButtonEnviar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar);
        jButtonEnviar.setBounds(560, 70, 110, 40);

        jButtonCancelar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(560, 130, 110, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 370, 710, 20);

        jTextProgreso.setColumns(20);
        jTextProgreso.setRows(5);
        jScrollPane2.setViewportView(jTextProgreso);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(170, 380, 340, 110);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Cuerpo;");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 240, 120, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRemitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRemitenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRemitenteActionPerformed

    private void jTextFieldAsuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAsuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAsuntoActionPerformed

    private void jTextFieldDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDestinatarioActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        if (this.jTextFieldDestinatario.getText().isEmpty() || this.jTextFieldRemitente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Se debe de escribir el destinatario y remitente antes de enviarlo");
        } else {
            String destino = this.jTextFieldDestinatario.getText();
            String remitente = this.jTextFieldRemitente.getText();
            Matcher mather1 = pattern.matcher(destino);
            Matcher mather2 = pattern.matcher(remitente);
            if (mather1.find()==false || mather2.find() == false) {
                JOptionPane.showMessageDialog(rootPane, "El destinatario y remitente no son correos validos");
            } else {
                if (this.jTextFieldAsunto.getText().isEmpty() || this.jTextCuerpo.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "El asunto y cuerpo del texto deben de ser escritos.");
                } else {
                    MensajeCorreo m=new MensajeCorreo(remitente, destino,this.jTextFieldAsunto.getText(),this.jTextCuerpo.getText());
                String log=this.fachada.enviarMensaje(m, tipo);
                this.jTextProgreso.setText(log);
                }
            }
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.jTextFieldDestinatario.setText("");
        this.jTextFieldRemitente.setText("");
        this.jTextCuerpo.setText("");
        this.jTextFieldAsunto.setText("");
        this.jTextProgreso.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextCuerpo;
    private javax.swing.JTextField jTextFieldAsunto;
    private javax.swing.JTextField jTextFieldDestinatario;
    private javax.swing.JTextField jTextFieldRemitente;
    private javax.swing.JTextArea jTextProgreso;
    // End of variables declaration//GEN-END:variables
}
